# Generated by Django 4.1 on 2023-05-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_post_update_at_alter_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=15)),
                ("name", models.CharField(max_length=50)),
                ("birth", models.DateField()),
                ("depart", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="exam/images/%Y/%m/%d/"),
                ),
            ],
        ),
        migrations.DeleteModel(name="Post",),
    ]
