# Generated by Django 4.1 on 2023-05-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_tag_rename_content_post_contents_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="post", old_name="contents", new_name="content",
        ),
        migrations.RenameField(
            model_name="post", old_name="update_at", new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="blog/images/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="blog/images/%Y/%m/%d/"),
        ),
    ]
